# Generated by Django 6.0.4 on 2026-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('allowance', models.FloatField()),
                ('days', models.IntegerField()),
                ('daily_limit', models.FloatField()),
                ('spent', models.FloatField(default=0)),
            ],
        ),
    ]
