# Generated by Django 6.0.5 on 2026-05-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masroofy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.FloatField()),
                ('current_amount', models.FloatField(default=0)),
            ],
        ),
    ]
