# Generated by Django 6.0.5 on 2026-05-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masroofy', '0002_savinggoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
